[workspace]
resolver = "2"
members = [
    "src-tauri",
    "vst/compressor",
    "vst/eq",
    "vst/limiter",
    "vst/bass",
    "vst/delay",
    "vst/reverb",
    "frost-core"
]

[workspace.dependencies]
symphonia = { version = "0.5", features = ["wav", "mp3"] }
parking_lot = "0.12"
cpal = "0.15.2"
ringbuf = "0.3.3"
lazy_static = "1.4.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
